package com.kingdee.eas.ma.budget.app;

import com.kingdee.bos.BOSException;
//import com.kingdee.bos.metadata.*;
import com.kingdee.bos.framework.*;
import com.kingdee.bos.util.*;
import com.kingdee.bos.Context;

import com.kingdee.bos.BOSException;
import java.util.Map;
import com.kingdee.bos.dao.IObjectPK;
import com.kingdee.eas.ma.budget.BgItemCollection;
import com.kingdee.bos.dao.IObjectCollection;
import com.kingdee.bos.framework.*;
import com.kingdee.bos.Context;
import com.kingdee.eas.ma.budget.BgItemInfo;
import java.util.Vector;
import com.kingdee.bos.metadata.entity.EntityViewInfo;
import com.kingdee.eas.ma.budget.BudgetRequestCategory;
import java.util.Set;
import java.util.ArrayList;
import com.kingdee.eas.ma.nbudget.BgElimTypeEnum;
import com.kingdee.bos.dao.IObjectValue;
import java.util.List;
import java.util.Hashtable;
import java.lang.String;
import com.kingdee.eas.ma.budget.BgCtrlResultCollection;
import com.kingdee.eas.ma.nbudget.BgDataRelationEnum;
import com.kingdee.eas.ma.budget.BgCtrlResultInfo;
import com.kingdee.eas.ma.budget.FpCashDirectionEnum;
import com.kingdee.eas.framework.app.TreeBaseController;
import java.math.BigDecimal;
import com.kingdee.eas.framework.CoreBaseInfo;
import com.kingdee.eas.framework.CoreBaseCollection;
import com.kingdee.bos.util.BOSUuid;
import com.kingdee.eas.common.EASBizException;
import com.kingdee.bos.metadata.entity.SelectorItemCollection;
import com.kingdee.bos.util.*;

import java.rmi.RemoteException;
import com.kingdee.bos.framework.ejb.BizController;

public interface BgItemController extends TreeBaseController
{
    public BgItemInfo getBgItemInfo(Context ctx, IObjectPK pk) throws BOSException, EASBizException, RemoteException;
    public BgItemInfo getBgItemInfo(Context ctx, IObjectPK pk, SelectorItemCollection selector) throws BOSException, EASBizException, RemoteException;
    public BgItemInfo getBgItemInfo(Context ctx, String oql) throws BOSException, EASBizException, RemoteException;
    public BgItemCollection getBgItemCollection(Context ctx) throws BOSException, RemoteException;
    public BgItemCollection getBgItemCollection(Context ctx, EntityViewInfo view) throws BOSException, RemoteException;
    public BgItemCollection getBgItemCollection(Context ctx, String oql) throws BOSException, RemoteException;
    public void removeAll(Context ctx, BOSUuid bgItemGroupId, BOSUuid orgUnitId) throws BOSException, EASBizException, RemoteException;
    public boolean isCreator(Context ctx, String creatorID, String groupID) throws BOSException, EASBizException, RemoteException;
    public String getMaxNumber(Context ctx, String startStr) throws BOSException, EASBizException, RemoteException;
    public void updateErrorData(Context ctx, Vector itemGroupNumberVec) throws BOSException, EASBizException, RemoteException;
    public void updateBgItemSuperior(Context ctx, Map bgItemInfo, boolean isInit) throws BOSException, EASBizException, RemoteException;
    public void removeBgItemSuperior(Context ctx, Map bgItemInfo) throws BOSException, EASBizException, RemoteException;
    public void removeBgItemSuperior(Context ctx) throws BOSException, EASBizException, RemoteException;
    public void updateBgItemSuperiorValue(Context ctx, BOSUuid orgUnitID, BOSUuid bgSchemeID, String formula, BigDecimal value) throws BOSException, EASBizException, RemoteException;
    public void updateBgItemSuperiorValue(Context ctx, BOSUuid orgUnitID, BOSUuid bgSchemeID, List formula, BigDecimal value) throws BOSException, EASBizException, RemoteException;
    public void updateBgItemSuperiorValue(Context ctx, BOSUuid orgUnitID, BOSUuid bgSchemeID, List formula, List value) throws BOSException, EASBizException, RemoteException;
    public boolean bgItemSupriorMaintenance(Context ctx) throws BOSException, EASBizException, RemoteException;
    public boolean importBgItemCollection(Context ctx, BOSUuid bgItemGroupId, BgItemCollection bgItemCollection) throws BOSException, EASBizException, RemoteException;
    public boolean checkBgItemCollection(Context ctx, BOSUuid bgItemGroupId, BgItemCollection bgItemCollection) throws BOSException, EASBizException, RemoteException;
    public void setItemInefficacy(Context ctx, String id) throws BOSException, EASBizException, RemoteException;
    public void setItemEfficacy(Context ctx, String id) throws BOSException, EASBizException, RemoteException;
    public boolean isJunior(Context ctx, int orgUnitLevel, String itemGroupID) throws BOSException, EASBizException, RemoteException;
    public void modifyBgItemOrg(Context ctx, Hashtable itemMap, Hashtable itemLongNumberMap, Hashtable itemTargetOrgMap, Hashtable itemNameMap, Hashtable itemNumberMap) throws BOSException, EASBizException, RemoteException;
    public boolean updateName(Context ctx, BgItemInfo info) throws BOSException, RemoteException;
    public void updateBgItemSuperiorCtrlRecord(Context ctx, BOSUuid orgUnitID, BOSUuid bgSchemeID, List formulaList, BgCtrlResultInfo record, BudgetRequestCategory category) throws BOSException, EASBizException, RemoteException;
    public void updateBgItemSuperiorCtrlRecord(Context ctx, BOSUuid orgUnitID, BOSUuid bgSchemeID, String formula, BgCtrlResultInfo record, BudgetRequestCategory category) throws BOSException, EASBizException, RemoteException;
    public void batchSetItemInefficacy(Context ctx, List bgItems) throws BOSException, EASBizException, RemoteException;
    public void batchSetItemEfficacy(Context ctx, List bgItems) throws BOSException, EASBizException, RemoteException;
    public Map getBatchBgItemName(Context ctx, BOSUuid orgUnitId, BOSUuid bgItemGroupId) throws BOSException, EASBizException, RemoteException;
    public Map getBatchBgItemName(Context ctx, BOSUuid orgUnitId, BOSUuid parentId, int level) throws BOSException, EASBizException, RemoteException;
    public IObjectValue getBgItemName(Context ctx, BOSUuid orgUnitId, String number) throws BOSException, EASBizException, RemoteException;
    public void deleteBgItemName(Context ctx, BOSUuid orgUnitId, BOSUuid bgItemId) throws BOSException, EASBizException, RemoteException;
    public void deleteBgItemName(Context ctx, List orgUnitIds, BOSUuid bgItemId) throws BOSException, EASBizException, RemoteException;
    public Map importItems(Context ctx, BgItemCollection itemCol, String orgUnitId, String importSource) throws BOSException, EASBizException, RemoteException;
    public void sumBgItemSuperiorCtrlRecord(Context ctx, BOSUuid orgUnitID, BOSUuid bgSchemeID, String formula, BgCtrlResultInfo resultInfo) throws BOSException, EASBizException, RemoteException;
    public BgCtrlResultCollection getSuperiorItemCtrlData(Context ctx, BgCtrlResultCollection ctrlResultCol) throws BOSException, EASBizException, RemoteException;
    public String updateFpDirection(Context ctx, ArrayList headId, FpCashDirectionEnum fpDirection) throws BOSException, EASBizException, RemoteException;
    public String updateSumFormula(Context ctx, IObjectValue model) throws BOSException, EASBizException, RemoteException;
    public IObjectCollection getItemListBySumItemFormula(Context ctx, String sumItemFormula) throws BOSException, EASBizException, RemoteException;
    public void batchUpdateSumFormula(Context ctx, List updateSumFormulas) throws BOSException, EASBizException, RemoteException;
    public Map checkExpIsUpdate(Context ctx, IObjectPK pk, IObjectValue newValue) throws BOSException, EASBizException, RemoteException;
    public String updateElimType(Context ctx, ArrayList headId, BgElimTypeEnum elimType, BgDataRelationEnum dataRela) throws BOSException, EASBizException, RemoteException;
    public String judgeRef(Context ctx, String number, String orgUnitId) throws BOSException, EASBizException, RemoteException;
    public void delete(Context ctx, IObjectPK[] arrayPK, String curOrgUnitId) throws BOSException, EASBizException, RemoteException;
    public void getSuperiorItems(Context ctx, BOSUuid orgUnitID, String formula, Set reFormulaList) throws BOSException, RemoteException;
}