package com.kingdee.eas.ma.budget;

import com.kingdee.bos.BOSException;
//import com.kingdee.bos.metadata.*;
import com.kingdee.bos.framework.*;
import com.kingdee.bos.util.*;
import com.kingdee.bos.Context;

import com.kingdee.eas.ma.nbudget.BgElimTypeEnum;
import java.util.ArrayList;
import com.kingdee.bos.dao.IObjectValue;
import com.kingdee.eas.framework.ITreeBase;
import com.kingdee.bos.BOSException;
import java.util.Map;
import java.util.List;
import com.kingdee.bos.dao.IObjectPK;
import com.kingdee.bos.dao.IObjectCollection;
import java.util.Hashtable;
import java.lang.String;
import com.kingdee.bos.framework.*;
import com.kingdee.eas.ma.nbudget.BgDataRelationEnum;
import com.kingdee.bos.Context;
import java.util.Vector;
import com.kingdee.bos.metadata.entity.EntityViewInfo;
import java.math.BigDecimal;
import com.kingdee.eas.framework.CoreBaseInfo;
import com.kingdee.eas.framework.CoreBaseCollection;
import java.util.Set;
import com.kingdee.bos.util.BOSUuid;
import com.kingdee.eas.common.EASBizException;
import com.kingdee.bos.util.*;
import com.kingdee.bos.metadata.entity.SelectorItemCollection;

public interface IBgItem extends ITreeBase
{
    public BgItemInfo getBgItemInfo(IObjectPK pk) throws BOSException, EASBizException;
    public BgItemInfo getBgItemInfo(IObjectPK pk, SelectorItemCollection selector) throws BOSException, EASBizException;
    public BgItemInfo getBgItemInfo(String oql) throws BOSException, EASBizException;
    public BgItemCollection getBgItemCollection() throws BOSException;
    public BgItemCollection getBgItemCollection(EntityViewInfo view) throws BOSException;
    public BgItemCollection getBgItemCollection(String oql) throws BOSException;
    public void removeAll(BOSUuid bgItemGroupId, BOSUuid orgUnitId) throws BOSException, EASBizException;
    public boolean isCreator(String creatorID, String groupID) throws BOSException, EASBizException;
    public String getMaxNumber(String startStr) throws BOSException, EASBizException;
    public void updateErrorData(Vector itemGroupNumberVec) throws BOSException, EASBizException;
    public void updateBgItemSuperior(Map bgItemInfo, boolean isInit) throws BOSException, EASBizException;
    public void removeBgItemSuperior(Map bgItemInfo) throws BOSException, EASBizException;
    public void removeBgItemSuperior() throws BOSException, EASBizException;
    public void updateBgItemSuperiorValue(BOSUuid orgUnitID, BOSUuid bgSchemeID, String formula, BigDecimal value) throws BOSException, EASBizException;
    public void updateBgItemSuperiorValue(BOSUuid orgUnitID, BOSUuid bgSchemeID, List formula, BigDecimal value) throws BOSException, EASBizException;
    public void updateBgItemSuperiorValue(BOSUuid orgUnitID, BOSUuid bgSchemeID, List formula, List value) throws BOSException, EASBizException;
    public boolean bgItemSupriorMaintenance() throws BOSException, EASBizException;
    public boolean importBgItemCollection(BOSUuid bgItemGroupId, BgItemCollection bgItemCollection) throws BOSException, EASBizException;
    public boolean checkBgItemCollection(BOSUuid bgItemGroupId, BgItemCollection bgItemCollection) throws BOSException, EASBizException;
    public void setItemInefficacy(String id) throws BOSException, EASBizException;
    public void setItemEfficacy(String id) throws BOSException, EASBizException;
    public boolean isJunior(int orgUnitLevel, String itemGroupID) throws BOSException, EASBizException;
    public void modifyBgItemOrg(Hashtable itemMap, Hashtable itemLongNumberMap, Hashtable itemTargetOrgMap, Hashtable itemNameMap, Hashtable itemNumberMap) throws BOSException, EASBizException;
    public boolean updateName(BgItemInfo info) throws BOSException;
    public void updateBgItemSuperiorCtrlRecord(BOSUuid orgUnitID, BOSUuid bgSchemeID, List formulaList, BgCtrlResultInfo record, BudgetRequestCategory category) throws BOSException, EASBizException;
    public void updateBgItemSuperiorCtrlRecord(BOSUuid orgUnitID, BOSUuid bgSchemeID, String formula, BgCtrlResultInfo record, BudgetRequestCategory category) throws BOSException, EASBizException;
    public void batchSetItemInefficacy(List bgItems) throws BOSException, EASBizException;
    public void batchSetItemEfficacy(List bgItems) throws BOSException, EASBizException;
    public Map getBatchBgItemName(BOSUuid orgUnitId, BOSUuid bgItemGroupId) throws BOSException, EASBizException;
    public Map getBatchBgItemName(BOSUuid orgUnitId, BOSUuid parentId, int level) throws BOSException, EASBizException;
    public IObjectValue getBgItemName(BOSUuid orgUnitId, String number) throws BOSException, EASBizException;
    public void deleteBgItemName(BOSUuid orgUnitId, BOSUuid bgItemId) throws BOSException, EASBizException;
    public void deleteBgItemName(List orgUnitIds, BOSUuid bgItemId) throws BOSException, EASBizException;
    public Map importItems(BgItemCollection itemCol, String orgUnitId, String importSource) throws BOSException, EASBizException;
    public void sumBgItemSuperiorCtrlRecord(BOSUuid orgUnitID, BOSUuid bgSchemeID, String formula, BgCtrlResultInfo resultInfo) throws BOSException, EASBizException;
    public BgCtrlResultCollection getSuperiorItemCtrlData(BgCtrlResultCollection ctrlResultCol) throws BOSException, EASBizException;
    public String updateFpDirection(ArrayList headId, FpCashDirectionEnum fpDirection) throws BOSException, EASBizException;
    public String updateSumFormula(IObjectValue model) throws BOSException, EASBizException;
    public IObjectCollection getItemListBySumItemFormula(String sumItemFormula) throws BOSException, EASBizException;
    public void batchUpdateSumFormula(List updateSumFormulas) throws BOSException, EASBizException;
    public Map checkExpIsUpdate(IObjectPK pk, IObjectValue newValue) throws BOSException, EASBizException;
    public String updateElimType(ArrayList headId, BgElimTypeEnum elimType, BgDataRelationEnum dataRela) throws BOSException, EASBizException;
    public String judgeRef(String number, String orgUnitId) throws BOSException, EASBizException;
    public void delete(IObjectPK[] arrayPK, String curOrgUnitId) throws BOSException, EASBizException;
    public void getSuperiorItems(BOSUuid orgUnitID, String formula, Set reFormulaList) throws BOSException;
}